CreateVideoForYoutubeChannel/Controllers/PhoneController.cs
using CreateVideoForYoutubeChannel.Models;
using CreateVideoForYoutubeChannel.PPTGenerate;
using DocumentFormat.OpenXml.Packaging;
using HtmlAgilityPack;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;

namespace CreateVideoForYoutubeChannel.Controllers
{
    public class PhoneController : Controller
    {
        public IActionResult Index()
        {
            var model = new YouTubeModel();

            return View(model);
        }

        [HttpPost]
        public IActionResult Index(YouTubeModel model)
        {
            string result = "";
            string docItems = "";

            HttpWebRequest httpRequest = (HttpWebRequest)HttpWebRequest.Create(model.Url);
            httpRequest.Timeout = 10000;
            httpRequest.UserAgent = "Code Sample Web Client";
            httpRequest.Credentials = CredentialCache.DefaultCredentials;
            HttpWebResponse respone = (HttpWebResponse)httpRequest.GetResponse();
            StreamReader stream = new StreamReader(respone.GetResponseStream(), Encoding.UTF8);
            result = stream.ReadToEnd();

            var doc = new HtmlAgilityPack.HtmlDocument();
            doc.LoadHtml(result);

            HtmlNode productName = doc.DocumentNode.SelectSingleNode("//div[@class='baslik']//h1//a");
            model.ProductName = productName.InnerText;

            string filepath = @"C:\Yutup\PHONE\" + model.ProductName.Replace(" ", "").Replace("/", "").Trim() + ".txt";

            if (System.IO.File.Exists(filepath))
                System.IO.File.Delete(filepath);

            using (StreamWriter sw = System.IO.File.CreateText(filepath))
            {
                docItems += string.Format("Ürün->{0} \n", model.ProductName);
                docItems += string.Format("Url->{0} \n", model.Url);

                HtmlNode properties = doc.DocumentNode.SelectSingleNode("//div[@id='bilgiler']");

                if (properties != null)
                {
                    HtmlNodeCollection groups = doc.DocumentNode.SelectNodes(".//div[@id='grup']");

                    if (groups != null && groups.Count > 0)
                    {
                        string groupName = string.Empty;

                        for (int i = 0; i < groups.Count; i++)
                        {
                            HtmlNode newItem = groups[i];

                            groupName = newItem.SelectSingleNode(".//h3").InnerText;

                            docItems += string.Format("***{0}**** \n", groupName);

                            HtmlNode groupProperty = newItem.SelectSingleNode(".//ul[@class='grup']");

                            HtmlNodeCollection groupChilNodes = groupProperty.ChildNodes;

                            string propertyName = string.Empty;
                            string propertyValue = string.Empty;

                            foreach (var item2 in groupChilNodes)
                            {
                                if (item2.Name == "li")
                                {
                                    propertyName = item2.SelectSingleNode("strong").InnerText;
                                    propertyValue = item2.SelectSingleNode("span//a") != null ? item2.SelectSingleNode("span//a").InnerText.Replace("\n", "") : item2.SelectSingleNode("span//span").InnerText.Replace("\n", "");

                                    docItems += string.Format("{0}->{1} \n", propertyName, propertyValue);
                                }
                            }
                        }
                    }
                }

                sw.WriteLine(docItems);
            }

            ViewData["Message"] = "Dosya Başarıyla Oluşturulmuştur";

            return View(model);
        }

        public IActionResult PhoneVS()
        {
            return View();
        }

        [HttpPost]
        public IActionResult PhoneVS(PhoneVSModel phoneVSModel)
        {
            // PPT

            List<string> phone1Properties = new List<string>();
            List<string> phone2Properties = new List<string>();

            string filepathPhone1 = @"C:\Yutup\PHONE\" + phoneVSModel.Phone1.Replace(" ", "") + ".txt";
            string filepathPhone2 = @"C:\Yutup\PHONE\" + phoneVSModel.Phone2.Replace(" ", "") + ".txt";

            using (StreamReader rd = System.IO.File.OpenText(filepathPhone1))
            {
                while (!rd.EndOfStream)
                {
                    string str = rd.ReadLine();
                    phone1Properties.Add(str);
                }
            }

            using (StreamReader rd = System.IO.File.OpenText(filepathPhone2))
            {
                while (!rd.EndOfStream)
                {
                    string str = rd.ReadLine();
                    phone2Properties.Add(str);
                }
            }

            // just gets me the current location of the assembly to get a full path
            string fileName = @"C:\Yutup\PHONE\VS\VS_PPT_PHONE.pptx";

            // open the presentation in edit mode -> the bool parameter stands for 'isEditable'
            using (PresentationDocument document = PresentationDocument.Open(fileName, true))
            {
                string phone1NewItem = string.Empty;
                string phone2NewItem = string.Empty;

                foreach (var item in phone1Properties)
                {
                    phone1NewItem = string.Format("Product1_{0}", item.Split("->")[0].Replace(" ", "_").Replace("/", "").Replace("(", "").Replace(")", "").Replace(".", ""));

                    // going through the slides of the presentation
                    foreach (SlidePart slidePart in document.PresentationPart.SlideParts)
                    {
                        // searching for a text with the placeholder i want to replace
                        DocumentFormat.OpenXml.Drawing.Text text =
                            slidePart.RootElement.Descendants<DocumentFormat.OpenXml.Drawing.Text>().FirstOrDefault(x => x.Text == phone1NewItem);

                        // change the text
                        if (text != null)
                            text.Text = phone1Properties.FirstOrDefault(x => x.Contains(item)).Split("->")[1].Replace("Var", "Yes").Replace("Yok", "No").Replace("Milyon", "Million").Replace("Milyar", "Billion").Replace("Cam", "Glass").Replace("Alüminyum", "Aluminum").Replace("Gram", "Grams").Replace("Çekirdek", "Core").Replace("Kablosu", "Cable").Replace("Piksel", "Pixel").Replace("Çift Hat", "Dual SIM").Replace("Ocak", "January").Replace("Şubat", "February").Replace("Mart", "March").Replace("Nisan", "April").Replace("Mayıs", "May").Replace("Haziran", "June").Replace("Temmuz", "July").Replace("Ağustos", "August").Replace("Eylül", "September").Replace("Ekim", "October").Replace("Kasım", "November").Replace("Aralık", "December").Replace("Depolama seçeneği var", "Storage Option").Replace("Paslanmaz Çelik", "Non Rusting Steel").Replace("Çift Batarya", "Dual Battery").Replace("seçeneği var", "Option").Replace("Ekran İçinde", "Under-Display").Replace("Tek Hat", "Single SIM").Replace("İnç", "Inch").Replace("Polikarbonat", "Polycarbonate").Replace("Yan Tarafta", "On the Side").Replace("Plastik", "Plastic").Replace("Metalik Görünümlü", "Metallic Look").Replace("Sadece Sıçramalara Karşı", "Splashproof Only").Replace("Glass Görünümlü", "Glass Look").Replace("Arka Kapakta", "On Back Cover");
                    }
                }

                foreach (var item in phone2Properties)
                {
                    phone2NewItem = string.Format("Product2_{0}", item.Split("->")[0].Replace(" ", "_").Replace("/", "").Replace("(", "").Replace(")", "").Replace(".", ""));

                    // going through the slides of the presentation
                    foreach (SlidePart slidePart in document.PresentationPart.SlideParts)
                    {
                        // searching for a text with the placeholder i want to replace
                        DocumentFormat.OpenXml.Drawing.Text text =
                            slidePart.RootElement.Descendants<DocumentFormat.OpenXml.Drawing.Text>().FirstOrDefault(x => x.Text == phone2NewItem);

                        // change the text
                        if (text != null)
                            text.Text = phone2Properties.FirstOrDefault(x => x.Contains(item)).Split("->")[1].Replace("Var", "Yes").Replace("Yok", "No").Replace("Milyon", "Million").Replace("Milyar", "Billion").Replace("Cam", "Glass").Replace("Alüminyum", "Aluminum").Replace("Gram", "Grams").Replace("Çekirdek", "Core").Replace("Kablosu", "Cable").Replace("Piksel", "Pixel").Replace("Çift Hat", "Dual SIM").Replace("Ocak", "January").Replace("Şubat", "February").Replace("Mart", "March").Replace("Nisan", "April").Replace("Mayıs", "May").Replace("Haziran", "June").Replace("Temmuz", "July").Replace("Ağustos", "August").Replace("Eylül", "September").Replace("Ekim", "October").Replace("Kasım", "November").Replace("Aralık", "December").Replace("Depolama seçeneği var", "Storage Option").Replace("Paslanmaz Çelik", "Non Rusting Steel").Replace("Çift Batarya", "Dual Battery").Replace("seçeneği var", "Option").Replace("Ekran İçinde", "Under-Display").Replace("Tek Hat", "Single SIM").Replace("İnç", "Inch").Replace("Polikarbonat", "Polycarbonate").Replace("Yan Tarafta", "On the Side").Replace("Plastik", "Plastic").Replace("Metalik Görünümlü", "Metallic Look").Replace("Sadece Sıçramalara Karşı", "Splashproof Only").Replace("Glass Görünümlü", "Glass Look").Replace("Arka Kapakta", "On Back Cover");
                    }
                }

                document.Save();
            }

            const string srcFileName = @"C:\Yutup\PHONE\VS\VS_PPT_PHONE.pptx";
            Pptx pptx = new Pptx(srcFileName, FileAccess.ReadWrite);
            int nbSlides = pptx.SlidesCount();
            

CreateVideoForYoutubeChannel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Youtube Video Creator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Phone
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" asp-area="" asp-controller="Phone" asp-action="Index">Get Data</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Phone" asp-action="PhoneVS">Compare Data</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            PowerBank
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" asp-area="" asp-controller="PowerBank" asp-action="Index">Get Data</a>
                            <a class="dropdown-item" asp-area="" asp-controller="PowerBank" asp-action="PowerBankVS">Compare Data</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Robot Vacuum
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" asp-area="" asp-controller="RobotVacuum" asp-action="Index">Get Data</a>
                            <a class="dropdown-item" asp-area="" asp-controller="RobotVacuum" asp-action="RobotVacuumVS">Compare Data</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Tablet
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" asp-area="" asp-controller="Tablet" asp-action="Index">Get Data</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Tablet" asp-action="TabletVS">Compare Data</a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Youtube Video Creator - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>